version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nebula-web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Ensure Celery & Django know the broker
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TIME_ZONE=Europe/London
    depends_on:
      - redis
    volumes:
      - .:/app  # hot-reload code changes in dev

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nebula-worker
    command: celery -A config worker -l info -P solo
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TIME_ZONE=Europe/London
    depends_on:
      - redis
    volumes:
      - .:/app

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nebula-beat
    command: celery -A config beat -l info
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TIME_ZONE=Europe/London
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:7
    container_name: nebula-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata:
