# Generated by Django 5.2.1 on 2025-08-20 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('module', '0001_initial'),
        ('program', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='module.module'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='program_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='program.programlevel'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='program.session'),
        ),
        migrations.AddField(
            model_name='lessonattendance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='classes.lesson'),
        ),
        migrations.AddField(
            model_name='lessonattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessoncomment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='classes.lesson'),
        ),
        migrations.AddField(
            model_name='lessoncomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='classes.lessoncomment'),
        ),
        migrations.AddField(
            model_name='lessoncomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonmaterial',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='classes.lesson'),
        ),
        migrations.AddField(
            model_name='lessonmaterial',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_lesson_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonquiz',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonquiz',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='classes.lesson'),
        ),
        migrations.AddField(
            model_name='lessonquizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='classes.lessonquiz'),
        ),
        migrations.AddField(
            model_name='lessonquizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.lessonquizquestion'),
        ),
        migrations.AddField(
            model_name='lessonquizresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='classes.lessonquiz'),
        ),
        migrations.AddField(
            model_name='lessonquizresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_quiz_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonquizanswer',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='classes.lessonquizresult'),
        ),
        migrations.AddField(
            model_name='lessonrating',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='classes.lesson'),
        ),
        migrations.AddField(
            model_name='lessonrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='lessonattendance',
            unique_together={('lesson', 'user')},
        ),
        migrations.AddIndex(
            model_name='lessoncomment',
            index=models.Index(fields=['lesson', 'created_at'], name='classes_les_lesson__9e5a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoncomment',
            index=models.Index(fields=['parent', 'created_at'], name='classes_les_parent__0fd98b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonmaterial',
            unique_together={('lesson', 'title', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonquiz',
            unique_together={('lesson', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonquizresult',
            unique_together={('user', 'quiz')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonquizanswer',
            unique_together={('result', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonrating',
            unique_together={('lesson', 'user')},
        ),
    ]
