# Generated by Django 5.2.1 on 2025-08-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_provider',
            field=models.CharField(choices=[('NONE', 'None'), ('CLOUDFLARE', 'Cloudflare Stream')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_provider_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_status',
            field=models.CharField(default='NONE', max_length=32),
        ),
    ]
