# Generated by Django 5.2.1 on 2025-08-28 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='program_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='program.programlevel'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('program_level__isnull', False), ('role', 'ENROLLED')), models.Q(('role', 'ENROLLED'), _negated=True), _connector='OR'), name='enrolled_requires_program_level'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('program_category__isnull', False), ('role', 'FREE')), models.Q(('role', 'FREE'), _negated=True), _connector='OR'), name='free_requires_program_category'),
        ),
    ]
