# Generated by Django 5.2.1 on 2025-08-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='location',
        ),
    ]
