# Generated by Django 5.2.1 on 2025-08-12 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_standalone', models.BooleanField(default=False, help_text='Can be taken without full program enrollment')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LectureMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('audience', models.CharField(choices=[('FREE', 'Free Users'), ('ENROLLED', 'Enrolled Students')], max_length=8)),
                ('title', models.CharField(max_length=150)),
                ('slides', models.FileField(upload_to='modules/slides/')),
                ('video_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='module.module')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('QUIZ', 'Quiz'), ('EXAM', 'Exam'), ('PROJECT', 'Project')], max_length=7)),
                ('title', models.CharField(max_length=150)),
                ('is_required', models.BooleanField(default=True, help_text='Is this component mandatory for module completion')),
                ('max_score', models.PositiveIntegerField(default=100, help_text='Maximum score for this component')),
                ('deadline', models.DateTimeField(blank=True, help_text='Deadline for submission', null=True)),
                ('criteria', models.JSONField(default=dict, help_text='Pass criteria JSON schema')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Relative weight of this component for module completion', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='module.module')),
            ],
            options={
                'ordering': ['type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ModuleLevelLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programlevel')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.module')),
            ],
            options={
                'ordering': ['level', 'order'],
                'unique_together': {('module', 'level')},
            },
        ),
        migrations.AddField(
            model_name='module',
            name='levels',
            field=models.ManyToManyField(help_text='Program levels this module belongs to', related_name='modules', through='module.ModuleLevelLink', to='program.programlevel'),
        ),
        migrations.CreateModel(
            name='ModuleLecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.module')),
            ],
            options={
                'unique_together': {('module', 'lecturer')},
            },
        ),
    ]
