# Generated by Django 5.2.1 on 2025-08-12 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.DateTimeField(db_index=True, help_text='UTC minute representing activity interval')),
                ('page', models.CharField(blank=True, max_length=128)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_pings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-minute'],
                'indexes': [models.Index(fields=['user', 'minute'], name='engagement__user_id_e92ce1_idx')],
                'unique_together': {('user', 'minute')},
            },
        ),
    ]
