# Generated by Django 5.2.1 on 2025-08-20 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('module', '0001_initial'),
        ('program', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='level',
            field=models.ForeignKey(blank=True, help_text='Optional level (must belong to the selected Program).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='program.programlevel'),
        ),
        migrations.AddField(
            model_name='application',
            name='module',
            field=models.ForeignKey(blank=True, help_text='For MODULE applications.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='module.module'),
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.ForeignKey(blank=True, help_text='For PROGRAM applications.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='program.program'),
        ),
        migrations.AddField(
            model_name='application',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='application.application'),
        ),
        migrations.AddField(
            model_name='applicationreview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='application.application'),
        ),
        migrations.AddField(
            model_name='applicationreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('module__isnull', True), ('program__isnull', False), ('type', 'PROGRAM')), models.Q(('type', 'PROGRAM'), _negated=True), _connector='OR'), name='app_program_requires_program_no_module'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('level__isnull', True), ('module__isnull', False), ('program__isnull', True), ('type', 'MODULE')), models.Q(('type', 'MODULE'), _negated=True), _connector='OR'), name='app_module_requires_module_no_program'),
        ),
        migrations.AddIndex(
            model_name='applicationevent',
            index=models.Index(fields=['application', 'created_at'], name='application_applica_fc89a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationreview',
            unique_together={('application', 'reviewer')},
        ),
    ]
