# Generated by Django 5.2.1 on 2025-08-12 11:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('ARTICLE', 'Write and publish an article'), ('LESSON', 'Attend a lesson'), ('TIME_SPENT', 'Accumulate X hours of learning'), ('QUIZ', 'Complete a quiz'), ('WORKSHEET', 'Submit a worksheet')], max_length=20)),
                ('required_hours', models.PositiveIntegerField(default=0, help_text='For TIME_SPENT task type only')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('progress', models.JSONField(blank=True, default=dict)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='badgetasks.weeklytask')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
