# Generated by Django 5.2.1 on 2025-08-20 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badgetasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklytaskassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='weeklytaskassignment',
            index=models.Index(fields=['user', 'week_start'], name='badgetasks__user_id_fab60f_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklytaskassignment',
            index=models.Index(fields=['user', 'status', 'week_start'], name='badgetasks__user_id_d3ce95_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklytaskassignment',
            unique_together={('user', 'task', 'week_start')},
        ),
    ]
