# Generated by Django 5.2.1 on 2025-08-15 23:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import worksheet.models.upload_paths
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=worksheet.models.upload_paths.worksheet_file_upload_path)),
                ('external_url', models.URLField(blank=True, help_text='If hosted externally (optional)')),
                ('instructions', models.TextField(blank=True)),
                ('audience', models.CharField(choices=[('ENROLLED', 'Enrolled Students Only'), ('FREE', 'Free Users'), ('BOTH', 'Both Enrolled and Free Users')], default='BOTH', help_text='Who can view/submit this worksheet', max_length=10)),
                ('format', models.CharField(choices=[('FILE', 'File Upload'), ('LINK', 'External Link'), ('INTERACTIVE', 'Interactive Form')], default='FILE', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheet', to='classes.lesson')),
                ('uploaded_by', models.ForeignKey(limit_choices_to={'role__in': ['LECTURER', 'VOLUNTEER', 'GUEST']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_worksheet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorksheetSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_file', models.FileField(blank=True, null=True, upload_to=worksheet.models.upload_paths.submission_upload_path)),
                ('written_response', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Optional score (e.g. out of 100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('RESUBMITTED', 'Resubmitted')], default='SUBMITTED', help_text='Current status of the submission', max_length=20)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['LECTURER', 'VOLUNTEER', 'GUEST']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksheet_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheet_submissions', to=settings.AUTH_USER_MODEL)),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='worksheet.worksheet')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('worksheet', 'user')},
            },
        ),
    ]
