# Generated by Django 5.2.1 on 2025-08-12 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('certificate_type', models.CharField(choices=[('PROGRAM_COMPLETION', 'Program Completion'), ('MODULE_COMPLETION', 'Module Completion'), ('MERIT', 'Special Recognition'), ('PARTICIPATION', 'Participation')], default='PROGRAM_COMPLETION', max_length=30)),
                ('background_image', models.ImageField(blank=True, help_text='Optional certificate background', null=True, upload_to='certificates/backgrounds/')),
                ('layout_config', models.JSONField(default=dict, help_text='Positioning info for name, date, program, etc.')),
                ('criteria', models.JSONField(default=dict, help_text="e.g., {'modules_required': 3, 'min_score': 80}")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('PROGRAM_COMPLETION', 'Program Completion'), ('MODULE_COMPLETION', 'Module Completion'), ('MERIT', 'Special Recognition'), ('PARTICIPATION', 'Participation')], max_length=30)),
                ('awarded_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('certificate_id', models.CharField(max_length=50, unique=True)),
                ('file', models.FileField(blank=True, help_text='Optional: Path to generated certificate PDF', null=True, upload_to='certificates/generated/')),
                ('is_downloaded', models.BooleanField(default=False)),
                ('downloaded_on', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-awarded_on'],
            },
        ),
    ]
