# Generated by Django 5.2.1 on 2025-08-15 23:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('certificate_type', models.CharField(choices=[('PROGRAM_COMPLETION', 'Program Completion'), ('MODULE_COMPLETION', 'Module Completion'), ('MERIT', 'Special Recognition'), ('PARTICIPATION', 'Participation')], default='PROGRAM_COMPLETION', max_length=30)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificates/backgrounds/')),
                ('layout_config', models.JSONField(default=dict, help_text='Positioning info for name, date, program, etc.')),
                ('criteria', models.JSONField(default=dict, help_text="e.g., {'levels_required': 'ALL', 'min_gpa': 4.0}")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('PROGRAM_COMPLETION', 'Program Completion'), ('MODULE_COMPLETION', 'Module Completion'), ('MERIT', 'Special Recognition'), ('PARTICIPATION', 'Participation')], max_length=30)),
                ('specialization_label', models.CharField(blank=True, max_length=120)),
                ('grade', models.CharField(choices=[('FIRST', 'First Class'), ('SECOND_UPPER', 'Second Class Upper'), ('SECOND_LOWER', 'Second Class Lower'), ('DISTINCTION', 'Distinction'), ('MERIT', 'Merit'), ('PASS', 'Pass'), ('UNGRADED', 'Ungraded')], default='UNGRADED', max_length=20)),
                ('session_label', models.CharField(help_text="e.g., 'Spring 2025' or '2024/2025'", max_length=64)),
                ('year_of_completion', models.PositiveSmallIntegerField()),
                ('completed_at', models.DateTimeField(help_text='When the criteria were satisfied')),
                ('awarded_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('serial', models.CharField(max_length=50, unique=True)),
                ('verify_token', models.CharField(max_length=64, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/generated/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ISSUED', 'Issued'), ('REVOKED', 'Revoked')], default='ISSUED', max_length=16)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-awarded_on'],
            },
        ),
    ]
