# Generated by Django 5.2.1 on 2025-08-28 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificate', '0001_initial'),
        ('module', '0001_initial'),
        ('program', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='program',
            field=models.ForeignKey(blank=True, help_text='For PROGRAM_COMPLETION templates, link the owning Program.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='program.program'),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='certificates', to='module.module'),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_certificates', to='program.program'),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_revoked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate.certificatetemplate'),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='certificatetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('certificate_type', 'PROGRAM_COMPLETION')), fields=('program',), name='uniq_program_completion_template_per_program'),
        ),
        migrations.AddIndex(
            model_name='usercertificate',
            index=models.Index(fields=['program', 'year_of_completion'], name='certificate_program_5848f0_idx'),
        ),
        migrations.AddIndex(
            model_name='usercertificate',
            index=models.Index(fields=['serial'], name='certificate_serial_0ab267_idx'),
        ),
        migrations.AddIndex(
            model_name='usercertificate',
            index=models.Index(fields=['verify_token'], name='certificate_verify__27486b_idx'),
        ),
    ]
