# Generated by Django 5.2.1 on 2025-08-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingsurvey',
            name='accept_privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingsurvey',
            name='privacy_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingsurvey',
            name='privacy_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='onboardingsurvey',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingsurvey',
            name='terms_version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
