# Generated by Django 5.2.1 on 2025-08-30 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('CLOUDFLARE', 'Cloudflare Stream'), ('YOUTUBE', 'YouTube'), ('MUX', 'Mux'), ('AWS', 'AWS MediaConvert')], default='CLOUDFLARE', max_length=20)),
                ('provider_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='UPLOADING', max_length=32)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primary_video', to='classes.lesson')),
            ],
        ),
    ]
