# Generated by Django 5.2.1 on 2025-08-20 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achievement', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='awardedbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='badge',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='badge',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Optional. Badge is specific to a module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges', to='module.module'),
        ),
        migrations.AddField(
            model_name='awardedbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievement.badge'),
        ),
        migrations.AddField(
            model_name='badgeawardlog',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievement.badge'),
        ),
        migrations.AddField(
            model_name='badgeawardlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofileachievement',
            name='current_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='achievement.userlevel'),
        ),
        migrations.AddField(
            model_name='userprofileachievement',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='xpevent',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='achievement.badge'),
        ),
        migrations.AddField(
            model_name='xpevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='awardedbadge',
            unique_together={('user', 'badge')},
        ),
    ]
